languageCode = "en-us"
title = "What She Doesn't Know"
rssLimit = 20
copyright = "Credit where credit is due - theme made by [sharadcodes](https://github.com/sharadcodes/hugo-theme-serial-programmer)"
minify = false

[Author]
  name = "Sanyia Saidova"
  email = "sanyia.saidova@gmail.com"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]